// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package sqlcdb

import (
	"context"
)

const getAllStats = `-- name: GetAllStats :many
SELECT question_id, total_attempts, correct_count
FROM question_statistics
ORDER BY question_id
`

func (q *Queries) GetAllStats(ctx context.Context) ([]QuestionStatistic, error) {
	rows, err := q.db.Query(ctx, getAllStats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QuestionStatistic
	for rows.Next() {
		var i QuestionStatistic
		if err := rows.Scan(&i.QuestionID, &i.TotalAttempts, &i.CorrectCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertQuestionStat = `-- name: UpsertQuestionStat :exec
INSERT INTO question_statistics (question_id, total_attempts, correct_count)
VALUES ($1, 1, $2)
ON CONFLICT (question_id) DO UPDATE
SET total_attempts = question_statistics.total_attempts + 1,
    correct_count  = question_statistics.correct_count + $2
`

type UpsertQuestionStatParams struct {
	QuestionID   string
	CorrectCount int32
}

func (q *Queries) UpsertQuestionStat(ctx context.Context, arg UpsertQuestionStatParams) error {
	_, err := q.db.Exec(ctx, upsertQuestionStat, arg.QuestionID, arg.CorrectCount)
	return err
}

const getHardestStats = `-- name: GetHardestStats :many
SELECT question_id, total_attempts, correct_count
FROM question_statistics
WHERE total_attempts > 0
ORDER BY CAST(correct_count AS FLOAT) / total_attempts ASC,
         total_attempts DESC
LIMIT 50
`

func (q *Queries) GetHardestStats(ctx context.Context) ([]QuestionStatistic, error) {
	rows, err := q.db.Query(ctx, getHardestStats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QuestionStatistic
	for rows.Next() {
		var i QuestionStatistic
		if err := rows.Scan(&i.QuestionID, &i.TotalAttempts, &i.CorrectCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEasiestStats = `-- name: GetEasiestStats :many
SELECT question_id, total_attempts, correct_count
FROM question_statistics
WHERE total_attempts > 0
ORDER BY CAST(correct_count AS FLOAT) / total_attempts DESC,
         total_attempts DESC
LIMIT 50
`

func (q *Queries) GetEasiestStats(ctx context.Context) ([]QuestionStatistic, error) {
	rows, err := q.db.Query(ctx, getEasiestStats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QuestionStatistic
	for rows.Next() {
		var i QuestionStatistic
		if err := rows.Scan(&i.QuestionID, &i.TotalAttempts, &i.CorrectCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countTrackedQuestions = `-- name: CountTrackedQuestions :one
SELECT COUNT(*)::int AS count FROM question_statistics
`

func (q *Queries) CountTrackedQuestions(ctx context.Context) (int32, error) {
	var count int32
	err := q.db.QueryRow(ctx, countTrackedQuestions).Scan(&count)
	return count, err
}
