services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: quiz
      POSTGRES_PASSWORD: quiz
      POSTGRES_DB: quiz
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U quiz"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      PORT: "8080"
      QUESTIONS_BASE_URL: "https://raw.githubusercontent.com/leehosanganson/life-in-the-uk-quiz/refs/heads/main/data/questions" # if set, overrides DATA_DIR and loads questions from this remote base URL
      DATABASE_URL: postgres://quiz:quiz@db:5432/quiz
      CORS_ORIGINS: http://localhost:3000,http://localhost:5173
    ports:
      - "8080:8080"
    volumes:
      - ./data:/data:ro
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    # image: harbor.leehosanganson.dev/leehosanganson/life-in-the-uk-quiz-frontend:00c9a43
    ports:
      - "3000:80"
    environment:
      VITE_BACKEND_HOST: http://backend:8080
      GITHUB_URL: "https://github.com/leehosanganson/life-in-the-uk-quiz"
      CONTACT_EMAIL: "leehosanganson@gmail.com"
      OPERATOR_NAME: "Ho Sang Lee"
      POLICY_UPDATE_DATE: "5 April 2026"
      APP_VERSION: local
    depends_on:
      - backend

volumes:
  db_data:
